import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/Components/navbar";
import Footer from "@/Components/footer";
import NextTopLoader from 'nextjs-toploader';
import NotificationBar from "@/Components/notification";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (<>

     
      <NextTopLoader />
     
      <NavBar/> 
      <NotificationBar />
      {children}

   
       
       <Footer/>
       </>
  );
}
