import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "@/Components/navbar";
import Footer from "@/Components/footer";

import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NextTopLoader />
        <NavBar/>
      
       {children}
       
       <Footer/>
        </body>
        
    </html>
  );
}
